service: kamaleo

image: <your-username>/kamaleo

proxy:
  ssl: true
  app_port: 80

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

accessories:
  tunnel:
    image: linuxserver/openssh-server
    port: "2222:22"
    files:
      - "config/ssh/sshd_config:/etc/ssh/sshd_config"
      - "config/ssh/authorized_keys:/config/authorized_keys"
    env:
      clear:
        USER_NAME: kamaleo